apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: longest-prefix-routes
spec:
  host: path-matching-vsr.example.com
  subroutes:
  - path: "^~/static/css/"
    action:
      return:
        code: 200
        type: text/plain
        body: 'LONGEST PREFIX SUBROUTE MATCH (^~)\nPath Directive:      ^~/static/css/\nRequest URI:         ${request_uri}\nVirtualServerRoute:  longest-prefix-routes\nSubroutes under a ^~ parent must also use the ^~ modifier.\n'
  - path: "^~/static/js/"
    action:
      return:
        code: 200
        type: text/plain
        body: 'LONGEST PREFIX SUBROUTE MATCH (^~)\nPath Directive:      ^~/static/js/\nRequest URI:         ${request_uri}\nVirtualServerRoute:  longest-prefix-routes\nSubroutes under a ^~ parent must also use the ^~ modifier.\n'
