apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: path-matching-vsr
spec:
  host: path-matching-vsr.example.com
  routes:
  - path: /images/
    route: prefix-routes
  - path: "^~/static/"
    route: longest-prefix-routes
