apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: prefix-routes
spec:
  host: path-matching-vsr.example.com
  subroutes:
  - path: /images/thumbnails/
    action:
      return:
        code: 200
        type: text/plain
        body: 'PREFIX SUBROUTE MATCH\nPath Directive:      /images/thumbnails/\nRequest URI:         ${request_uri}\nVirtualServerRoute:  prefix-routes\nMatched a subroute under the /images/ parent route delegation.\n'
  - path: /images/originals/
    action:
      return:
        code: 200
        type: text/plain
        body: 'PREFIX SUBROUTE MATCH\nPath Directive:      /images/originals/\nRequest URI:         ${request_uri}\nVirtualServerRoute:  prefix-routes\nMatched a subroute under the /images/ parent route delegation.\n'
