{{- if and .Values.prometheusExtended.enabled .Values.prometheusExtended.serviceMonitor.enabled }}
{{- include "nginx-ingress.wallarm.serviceMonitor" (dict "metricsConfig" .Values.prometheusExtended "monitorSuffix" "prometheus-extended" "componentSelector" "controller" "context" .) -}}
{{- end -}}
