{{- if and .Values.config.wallarm.enabled .Values.controller.nginxStatus.enable -}}
{{- include "nginx-ingress.wallarm.serviceMonitor" (dict "metricsConfig" .Values.controller.wallarm.wd.metrics "monitorSuffix" "wallarm-wd" "componentSelector" "controller" "context" .) -}}
{{- end -}}
