{{- if .Values.config.wallarm.enabled -}}
{{- include "nginx-ingress.wallarm.serviceMonitor" (dict "metricsConfig" .Values.controller.wallarm.wcli.metrics "monitorSuffix" "wcli" "componentSelector" "controller" "context" .) -}}
{{- end -}}
