{{- if .Values.config.wallarm.enabled -}}
{{- include "nginx-ingress.wallarm.serviceMonitor" (dict "metricsConfig" .Values.controller.wallarm.metrics "monitorSuffix" "wallarm" "componentSelector" "controller" "context" .) -}}
{{- end -}}
