{{- if and .Values.config.wallarm.enabled .Values.controller.nginxStatus.enable -}}
{{- include "nginx-ingress.wallarm.metricsService" (dict "metricsConfig" .Values.controller.wallarm.wd.metrics "serviceSuffix" "wallarm-wd" "componentSelector" "controller" "context" .) -}}
{{- end -}}
