{{- if .Values.config.wallarm.enabled -}}
{{- include "nginx-ingress.wallarm.metricsService" (dict "metricsConfig" .Values.controller.wallarm.wcli.metrics "serviceSuffix" "wcli" "componentSelector" "controller" "context" .) -}}
{{- end -}}
