{{- if .Values.config.wallarm.enabled }}
{{- if eq .Values.postanalytics.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-wallarm-postanalytics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: wallarm-postanalytics
  {{- with .Values.postanalytics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.postanalytics.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-ingress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: wallarm-postanalytics
  template:
    metadata:
      labels:
        {{- include "nginx-ingress.podLabels" . | nindent 8 }}
        app.kubernetes.io/component: wallarm-postanalytics
      {{- with .Values.postanalytics.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        wallarm-enabled: "true"
        checksum/wd-config: {{ include (print $.Template.BasePath "/postanalytics-wd-configmap.yaml") . | sha256sum }}
{{- if not .Values.config.wallarm.api.existingSecret.enabled }}
        checksum/token: {{ .Values.config.wallarm.api.token | sha256sum }}
{{- end }}
      {{- with .Values.postanalytics.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.postanalytics.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx-ingress.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.postanalytics.terminationGracePeriodSeconds | default 30 }}
      initContainers:
      {{ include "nginx-ingress.wallarm.wdInitContainer" (dict "context" . "wdConfig" .Values.postanalytics.wd) | nindent 6 }}
      containers:
        {{ include "nginx-ingress.wallarm.wdContainer" (dict "context" . "wdConfig" .Values.postanalytics.wd "configMapName" (printf "%s-wallarm-postanalytics-wd" (include "nginx-ingress.fullname" .)) "mode" "postanalytics") | nindent 8 }}

      {{- with .Values.postanalytics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postanalytics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postanalytics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postanalytics.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{ include "nginx-ingress.wallarm.wdVolumes" (dict "context" . "configMapName" (printf "%s-wallarm-postanalytics-wd" (include "nginx-ingress.fullname" .))) | nindent 6 }}
      {{- with .Values.postanalytics.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
