{{- if .Values.config.wallarm.enabled -}}
{{- include "nginx-ingress.wallarm.metricsService" (dict "metricsConfig" .Values.postanalytics.wcli.metrics "serviceSuffix" "wcli-post" "componentSelector" (include "nginx-ingress.wallarm.postanalyticsName" .) "context" .) -}}
{{- end -}}
