{{- if and .Values.config.wallarm.enabled .Values.postanalytics.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-wallarm-postanalytics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: wallarm-postanalytics
{{- if .Values.postanalytics.podDisruptionBudget.annotations }}
  annotations:
{{ toYaml .Values.postanalytics.podDisruptionBudget.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nginx-ingress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: wallarm-postanalytics
{{- if .Values.postanalytics.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.postanalytics.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.postanalytics.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.postanalytics.podDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end }}
