{{- if .Values.config.wallarm.enabled -}}
{{- include "nginx-ingress.wallarm.metricsService" (dict "metricsConfig" .Values.postanalytics.wd.metrics "serviceSuffix" "wallarm-wd-post" "componentSelector" (include "nginx-ingress.wallarm.postanalyticsName" .) "context" .) -}}
{{- end -}}
