// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ExternalAuthApplyConfiguration represents a declarative configuration of the ExternalAuth type for use
// with apply.
//
// ExternalAuth defines an external authentication policy for authenticating client requests using an external authentication server, which can be used for example with the oauth2-proxy or any custom authentication server that requires redirection for authentication.
type ExternalAuthApplyConfiguration struct {
	// AuthURI is the URI of the external authentication server to which the request will be sent for authentication. The URI is a relative URI, for example /auth.
	AuthURI *string `json:"authURI,omitempty"`
	// AuthServiceName is the name of the Kubernetes service to which the request will be sent for authentication.  It can be in the same namespace as the Policy resource or in a different namespace. If the service is in a different namespace, it should be specified in the format <namespace>/<service>. For example, auth-service or auth-namespace/auth-service.
	AuthServiceName *string `json:"authServiceName,omitempty"`
	// AuthServicePorts are the ports of the Kubernetes service to which requests will be sent for authentication. If not specified, the ports will be looked up from the service definition. This field is only required if the user wants to choose a specific port from the service definition, otherwise the first port will be used by default.
	AuthServicePorts []int `json:"authServicePorts,omitempty"`
	// AuthSigninURI is the URI which requests will be redirected to if the external authentication server determines that the client needs to be authenticated. This is typically used when the external authentication server is an oauth2-proxy or any custom authentication server that requires redirection for authentication. The URI is a relative URI, for example /signin.
	AuthSigninURI *string `json:"authSigninURI,omitempty"`
	// AuthSnippets can be used to add custom configuration snippets to the location block of the external authentication configuration. This can be used for example to add additional headers to the request sent to the external authentication server, or to configure additional parameters for the auth_request module. The content of this field will be added as-is to the location block, so it must be a valid NGINX configuration snippet.
	AuthSnippets *string `json:"authSnippets,omitempty"`
	// AuthSigninRedirectBasePath is the base path for the NGINX location block that handles sign-in redirect requests from the external authentication server. For example, oauth2-proxy expects /oauth2. If not specified, defaults to /oauth2.
	AuthSigninRedirectBasePath *string `json:"authSigninRedirectBasePath,omitempty"`
	// SSLEnabled enables HTTPS when proxying requests to the external authentication server. Default is false.
	SSLEnabled *bool `json:"sslEnabled,omitempty"`
	// SSLVerify enables verification of the external authentication server's SSL certificate. Default is false.
	SSLVerify *bool `json:"sslVerify,omitempty"`
	// SSLVerifyDepth sets the verification depth in the external authentication server certificates chain. Default is 1.
	SSLVerifyDepth *int `json:"sslVerifyDepth,omitempty"`
	// TrustedCertSecret is the name of the Kubernetes secret that stores the CA certificate for external authentication server certificate verification. It can be in the same namespace as the Policy resource or in a different namespace specified as <namespace>/<secret>. The secret must be of the type nginx.org/ca, and the certificate must be stored under the key ca.crt.
	TrustedCertSecret *string `json:"trustedCertSecret,omitempty"`
	// SNIName sets the server name used for SNI and certificate verification when connecting to the external authentication server over TLS. If not specified, defaults to <service-name>.<namespace>.svc derived from authServiceName.
	SNIName *string `json:"sniName,omitempty"`
}

// ExternalAuthApplyConfiguration constructs a declarative configuration of the ExternalAuth type for use with
// apply.
func ExternalAuth() *ExternalAuthApplyConfiguration {
	return &ExternalAuthApplyConfiguration{}
}

// WithAuthURI sets the AuthURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthURI field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthURI(value string) *ExternalAuthApplyConfiguration {
	b.AuthURI = &value
	return b
}

// WithAuthServiceName sets the AuthServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthServiceName field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthServiceName(value string) *ExternalAuthApplyConfiguration {
	b.AuthServiceName = &value
	return b
}

// WithAuthServicePorts adds the given value to the AuthServicePorts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthServicePorts field.
func (b *ExternalAuthApplyConfiguration) WithAuthServicePorts(values ...int) *ExternalAuthApplyConfiguration {
	for i := range values {
		b.AuthServicePorts = append(b.AuthServicePorts, values[i])
	}
	return b
}

// WithAuthSigninURI sets the AuthSigninURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSigninURI field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthSigninURI(value string) *ExternalAuthApplyConfiguration {
	b.AuthSigninURI = &value
	return b
}

// WithAuthSnippets sets the AuthSnippets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSnippets field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthSnippets(value string) *ExternalAuthApplyConfiguration {
	b.AuthSnippets = &value
	return b
}

// WithAuthSigninRedirectBasePath sets the AuthSigninRedirectBasePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSigninRedirectBasePath field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthSigninRedirectBasePath(value string) *ExternalAuthApplyConfiguration {
	b.AuthSigninRedirectBasePath = &value
	return b
}

// WithSSLEnabled sets the SSLEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLEnabled field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithSSLEnabled(value bool) *ExternalAuthApplyConfiguration {
	b.SSLEnabled = &value
	return b
}

// WithSSLVerify sets the SSLVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLVerify field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithSSLVerify(value bool) *ExternalAuthApplyConfiguration {
	b.SSLVerify = &value
	return b
}

// WithSSLVerifyDepth sets the SSLVerifyDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLVerifyDepth field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithSSLVerifyDepth(value int) *ExternalAuthApplyConfiguration {
	b.SSLVerifyDepth = &value
	return b
}

// WithTrustedCertSecret sets the TrustedCertSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustedCertSecret field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithTrustedCertSecret(value string) *ExternalAuthApplyConfiguration {
	b.TrustedCertSecret = &value
	return b
}

// WithSNIName sets the SNIName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SNIName field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithSNIName(value string) *ExternalAuthApplyConfiguration {
	b.SNIName = &value
	return b
}
