apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: hsts-policy
spec:
  hsts:
    # sets how long in seconds the browser should cache and enforce the HSTS policy
    maxAge: 2592000
    # extends the policy to all subdomains of the host
    includeSubDomains: true
    # when behindProxy is true, the HSTS headers are set based on the X-Forwarded-Proto header
    behindProxy: false
    # when preload is true, the preload directive is added to the header allowing the site to be added to the browser HSTS preload lists
    preload: false
