apiVersion: v2
name: wallarm-ingress
version: 7.0.0-rc0
appVersion: 6.10.0
kubeVersion: ">= 1.25.0-0"
type: application
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer with Wallarm module (new)
icon: https://static.wallarm.com/wallarm-logo.svg
home: https://www.wallarm.com
sources:
  - https://github.com/wallarm/ingress
keywords:
  - ingress
  - nginx
  - wallarm
maintainers:
  - name: Wallarm Support Team
    email: support@wallarm.com
