// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/nginx/kubernetes-ingress/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// GlobalConfigurations returns a GlobalConfigurationInformer.
	GlobalConfigurations() TypedGlobalConfigurationInformer
	// Policies returns a PolicyInformer.
	Policies() TypedPolicyInformer
	// TransportServers returns a TransportServerInformer.
	TransportServers() TypedTransportServerInformer
	// VirtualServers returns a VirtualServerInformer.
	VirtualServers() TypedVirtualServerInformer
	// VirtualServerRoutes returns a VirtualServerRouteInformer.
	VirtualServerRoutes() TypedVirtualServerRouteInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// GlobalConfigurations returns a TypedGlobalConfigurationInformer.
func (v *version) GlobalConfigurations() TypedGlobalConfigurationInformer {
	return &globalConfigurationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Policies returns a TypedPolicyInformer.
func (v *version) Policies() TypedPolicyInformer {
	return &policyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TransportServers returns a TypedTransportServerInformer.
func (v *version) TransportServers() TypedTransportServerInformer {
	return &transportServerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VirtualServers returns a TypedVirtualServerInformer.
func (v *version) VirtualServers() TypedVirtualServerInformer {
	return &virtualServerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VirtualServerRoutes returns a TypedVirtualServerRouteInformer.
func (v *version) VirtualServerRoutes() TypedVirtualServerRouteInformer {
	return &virtualServerRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
