// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisconfigurationv1 "github.com/nginx/kubernetes-ingress/pkg/apis/configuration/v1"
	versioned "github.com/nginx/kubernetes-ingress/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nginx/kubernetes-ingress/pkg/client/informers/externalversions/internalinterfaces"
	configurationv1 "github.com/nginx/kubernetes-ingress/pkg/client/listers/configuration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PolicyInformer provides access to a shared informer and lister for
// Policies. Prefer using the type-safe variant (see [TypedPolicyInformer]).
type PolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() configurationv1.PolicyLister
}

// TypedPolicyInformer provides access to a shared informer and lister for
// Policies, including the type-safe TypedInformer variant.
// It is a superset of PolicyInformer.
type TypedPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() PolicyIndexInformer
	Lister() configurationv1.PolicyLister
}

// PolicyIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type PolicyIndexInformer cache.TypedSharedIndexInformer[*apisconfigurationv1.Policy]

// PolicyHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Policy.
type PolicyHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisconfigurationv1.Policy]

// PolicyDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Policy.
type PolicyDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisconfigurationv1.Policy]

// PolicyFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Policy.
type PolicyFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisconfigurationv1.Policy]

// PolicyIndexers is a specialization of [cache.TypedIndexers] for Policy.
type PolicyIndexers = cache.TypedIndexers[*apisconfigurationv1.Policy]

// DeletedPolicy is a specialization of [cache.DeletedObject] for Policy.
type DeletedPolicy = cache.DeletedObject[*apisconfigurationv1.Policy]

type policyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPolicyInformer constructs a new informer for Policy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPolicyInformer]).
func NewPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewPolicyInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedPolicyInformer constructs a new informer for Policy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers PolicyIndexers) PolicyIndexInformer {
	return NewTypedPolicyInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredPolicyInformer constructs a new informer for Policy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredPolicyInformer]).
func NewFilteredPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedPolicyInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredPolicyInformer constructs a new informer for Policy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers PolicyIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) PolicyIndexInformer {
	return NewTypedPolicyInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewPolicyInformerWithOptions constructs a new informer for Policy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPolicyInformerWithOptions]).
func NewPolicyInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedPolicyInformerWithOptions(client, namespace, options)
}

// NewTypedPolicyInformerWithOptions constructs a new informer for Policy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPolicyInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) PolicyIndexInformer {
	gvr := schema.GroupVersionResource{Group: "k8s.nginx.org", Version: "v1", Resource: "policys"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisconfigurationv1.Policy](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.K8sV1().Policies(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.K8sV1().Policies(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.K8sV1().Policies(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.K8sV1().Policies(namespace).Watch(ctx, opts)
			},
		}, client),
		&apisconfigurationv1.Policy{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *policyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedPolicyInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *policyInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *policyInformer) TypedInformer() PolicyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisconfigurationv1.Policy](f.factory.InformerFor(&apisconfigurationv1.Policy{}, f.defaultInformer))
}

func (f *policyInformer) Lister() configurationv1.PolicyLister {
	return configurationv1.NewPolicyLister(f.Informer().GetIndexer())
}

// ToTypedPolicyInformer converts an untyped informer into a TypedPolicyInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Policy. If that is not the case, calling type-safe methods of the returned
// TypedPolicyInformer leads to runtime panics. A safer alternative is to pass
// around a TypedPolicyInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedPolicyInformer(informer PolicyInformer) TypedPolicyInformer {
	if informer, ok := informer.(TypedPolicyInformer); ok {
		return informer
	}
	return &policyTypedInformerAdapter{informer}
}

type policyTypedInformerAdapter struct {
	PolicyInformer
}

func (a *policyTypedInformerAdapter) TypedInformer() PolicyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisconfigurationv1.Policy](a.Informer())
}

// ToPolicyIndexInformer converts an untyped informer into a PolicyIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Policy. If that is not the case, calling type-safe methods of the returned
// PolicyIndexInformer leads to runtime panics. A safer alternative is to pass
// around a PolicyIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToPolicyIndexInformer(informer cache.SharedIndexInformer) PolicyIndexInformer {
	if informer, ok := informer.(PolicyIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisconfigurationv1.Policy](informer)
}
