apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-client-secret
type: Opaque
data:
  # Replace this with the base64-encoded client secret from your GitHub OAuth App.
  # echo -n '<your-github-client-secret>' | base64
  client-secret: abcbase64==
