"""Utilities for WAF bundle source integration tests.

Provides helpers to deploy an in-cluster HTTPS bundle server using
pre-generated TLS secrets (from hack/secrets-gen) and to create WAF
Policy CRDs with apBundleSource.
"""

import logging
import os
import subprocess

from kubernetes.client import CoreV1Api, CustomObjectsApi
from kubernetes.client.rest import ApiException
from settings import TEST_DATA
from suite.utils.resources_utils import (
    create_items_from_yaml,
    create_secret_from_yaml,
    delete_items_from_yaml,
    delete_secret,
    wait_before_test,
    wait_until_all_pods_are_ready,
)

BUNDLE_SERVER_YAML = f"{TEST_DATA}/ap-waf-bundle-source/bundle-server.yaml"
WAF_BUNDLE_PATH = f"{TEST_DATA}/ap-waf-v5/wafv5.tgz"

# Pre-generated by make secrets (hack/secrets-gen), symlinked into tests/data/.
SECRET_DIR = f"{TEST_DATA}/ap-waf-bundle-source/secret"
SERVER_TLS_SECRET_YAML = f"{SECRET_DIR}/bundle-server-tls-secret.yaml"
CLIENT_TLS_SECRET_YAML = f"{SECRET_DIR}/bundle-client-tls-secret.yaml"
CA_SECRET_YAML = f"{SECRET_DIR}/bundle-server-ca-secret.yaml"

SECRET_NAME_SERVER_TLS = "bundle-server-tls"
SECRET_NAME_CLIENT_TLS = "bundle-client-tls"
SECRET_NAME_CA = "bundle-server-ca"

BUNDLE_SERVER_SECRETS = [SECRET_NAME_SERVER_TLS, SECRET_NAME_CLIENT_TLS, SECRET_NAME_CA]


class BundleServerSetup:
    """Holds connection info for the deployed HTTPS bundle server."""

    def __init__(self, insecure_url: str, mtls_url: str, client_secret: str, ca_secret: str):
        self.insecure_url = insecure_url
        self.mtls_url = mtls_url
        self.client_secret = client_secret
        self.ca_secret = ca_secret


def create_bundle_server_secrets(v1: CoreV1Api, namespace: str) -> None:
    """Create Kubernetes TLS secrets from pre-generated YAML files.

    The YAML files are produced by ``make secrets`` (hack/secrets-gen)
    and symlinked into tests/data/ap-waf-bundle-source/secret/.

    :param v1: CoreV1Api
    :param namespace: target namespace
    """
    for yaml_path in [SERVER_TLS_SECRET_YAML, CLIENT_TLS_SECRET_YAML, CA_SECRET_YAML]:
        create_secret_from_yaml(v1, namespace, yaml_path)


def deploy_bundle_server(kube_apis, namespace: str) -> None:
    """Deploy the HTTPS bundle server and copy the WAF bundle into it.

    Applies bundle-server.yaml (ConfigMap + Deployment + Services), waits
    for the pod to become ready, then streams wafv5.tgz into the pod.

    :param kube_apis: KubeApis fixture object
    :param namespace: target namespace
    """
    print("Deploy bundle server")
    create_items_from_yaml(kube_apis, BUNDLE_SERVER_YAML, namespace)
    wait_until_all_pods_are_ready(kube_apis.v1, namespace)
    _copy_bundle_to_pod(kube_apis.v1, namespace)


def _copy_bundle_to_pod(v1: CoreV1Api, namespace: str) -> None:
    """Copy the pre-compiled WAF bundle into the bundle-server pod.

    Uses kubectl cp which handles buffering and EOF signaling reliably,
    unlike the kubernetes python client's websocket stream which can
    truncate large files.
    """
    if not os.path.exists(WAF_BUNDLE_PATH):
        raise FileNotFoundError(f"WAF bundle not found: {WAF_BUNDLE_PATH}")

    pod_name = _get_bundle_server_pod(v1, namespace)
    dest_path = "/www/bundles/wafv5.tgz"
    print(f"Copy WAF bundle to bundle-server pod {pod_name}")

    result = subprocess.run(
        ["kubectl", "cp", WAF_BUNDLE_PATH, f"{namespace}/{pod_name}:{dest_path}", "-c", "nginx"],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        raise RuntimeError(f"kubectl cp failed: {result.stderr}")
    print("WAF bundle copied to bundle-server pod")


def _get_bundle_server_pod(v1: CoreV1Api, namespace: str) -> str:
    """Return the name of the bundle-server pod."""
    pods = v1.list_namespaced_pod(namespace, label_selector="app=bundle-server")
    if not pods.items:
        raise RuntimeError(f"No bundle-server pod found in namespace {namespace}")
    return pods.items[0].metadata.name


def teardown_bundle_server(kube_apis, namespace: str) -> None:
    """Remove the bundle server deployment and all associated secrets.

    :param kube_apis: KubeApis fixture object
    :param namespace: target namespace
    """
    print("Teardown bundle server")
    try:
        delete_items_from_yaml(kube_apis, BUNDLE_SERVER_YAML, namespace)
    except Exception as ex:
        logging.warning(f"Error deleting bundle server resources: {ex}")

    for secret_name in BUNDLE_SERVER_SECRETS:
        try:
            delete_secret(kube_apis.v1, secret_name, namespace)
        except ApiException as ex:
            if ex.status != 404:
                logging.warning(f"Error deleting secret {secret_name}: {ex}")


def create_waf_bundle_source_policy(
    custom_objects: CustomObjectsApi,
    namespace: str,
    name: str,
    url: str,
    *,
    enable_polling: bool = False,
    insecure_skip_verify: bool = False,
    secret: str = None,
    trusted_cert_secret: str = None,
) -> str:
    """Create a WAF Policy CRD with apBundleSource (built programmatically).

    :param custom_objects: CustomObjectsApi
    :param namespace: target namespace
    :param name: policy name
    :param url: bundle URL (must be https://)
    :param enable_polling: whether to enable background polling
    :param insecure_skip_verify: skip TLS certificate verification
    :param secret: name of kubernetes.io/tls secret for client mTLS
    :param trusted_cert_secret: name of nginx.org/ca secret for server CA verification
    :return: policy name
    """
    bundle_source = {
        "url": url,
        "enablePolling": enable_polling,
    }
    if insecure_skip_verify:
        bundle_source["insecureSkipVerify"] = True
    if secret:
        bundle_source["secret"] = secret
    if trusted_cert_secret:
        bundle_source["trustedCertSecret"] = trusted_cert_secret

    policy = {
        "apiVersion": "k8s.nginx.org/v1",
        "kind": "Policy",
        "metadata": {"name": name},
        "spec": {
            "waf": {
                "enable": True,
                "apBundleSource": bundle_source,
            }
        },
    }

    print(f"Create WAF bundle source policy: {name}")
    try:
        custom_objects.create_namespaced_custom_object(
            "k8s.nginx.org",
            "v1",
            namespace,
            "policies",
            policy,
        )
        print(f"WAF bundle source policy created: {name}")
    except ApiException:
        logging.exception(f"Failed to create WAF bundle source policy: {name}")
        raise

    return name


def patch_waf_bundle_source_policy(
    custom_objects: CustomObjectsApi,
    namespace: str,
    name: str,
    url: str,
    *,
    enable_polling: bool = False,
    insecure_skip_verify: bool = False,
    secret: str = None,
    trusted_cert_secret: str = None,
) -> None:
    """Patch an existing WAF Policy's apBundleSource URL and settings.

    Used for recovery tests where we switch from an invalid to a valid URL.
    """
    bundle_source = {
        "url": url,
        "enablePolling": enable_polling,
    }
    if insecure_skip_verify:
        bundle_source["insecureSkipVerify"] = True
    if secret:
        bundle_source["secret"] = secret
    if trusted_cert_secret:
        bundle_source["trustedCertSecret"] = trusted_cert_secret

    patch_body = {
        "spec": {
            "waf": {
                "enable": True,
                "apBundleSource": bundle_source,
            }
        },
    }

    print(f"Patch WAF bundle source policy: {name} with url={url}")
    custom_objects.patch_namespaced_custom_object(
        "k8s.nginx.org",
        "v1",
        namespace,
        "policies",
        name,
        patch_body,
    )
    print(f"WAF bundle source policy patched: {name}")


def bundle_server_insecure_url(namespace: str) -> str:
    """Return the TLS-only (no client auth) bundle URL for the given namespace."""
    return f"https://bundle-server.{namespace}.svc.cluster.local:8443/bundles/wafv5.tgz"


def bundle_server_mtls_url(namespace: str) -> str:
    """Return the mTLS bundle URL for the given namespace."""
    return f"https://bundle-server-mtls.{namespace}.svc.cluster.local/bundles/wafv5.tgz"


def setup_bundle_server(kube_apis, namespace: str) -> BundleServerSetup:
    """Full setup: create secrets from pre-generated YAML, deploy server, copy bundle.

    :param kube_apis: KubeApis fixture object
    :param namespace: target namespace
    :return: BundleServerSetup with URLs and secret names
    """
    create_bundle_server_secrets(kube_apis.v1, namespace)
    deploy_bundle_server(kube_apis, namespace)
    # Allow time for service endpoints to fully propagate (especially mTLS on port 443).
    wait_before_test(5)

    return BundleServerSetup(
        insecure_url=bundle_server_insecure_url(namespace),
        mtls_url=bundle_server_mtls_url(namespace),
        client_secret=SECRET_NAME_CLIENT_TLS,
        ca_secret=SECRET_NAME_CA,
    )
